# Generated by Django 5.1 on 2025-02-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                default="<django.db.models.fields.CharField> <django.db.models.fields.CharField>",
                max_length=120,
            ),
        ),
    ]
