# Generated by Django 5.1 on 2025-02-19 16:25

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(default="EG", max_length=2),
        ),
    ]
