# Generated by Django 5.1 on 2025-02-19 16:30

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_profile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+201234567891", max_length=128, region=None
            ),
        ),
    ]
