# Generated by Django 5.1 on 2025-02-19 16:34

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_profile_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(default="tanta", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+201234567891", max_length=30, region=None
            ),
        ),
        migrations.DeleteModel(
            name="cities",
        ),
    ]
