# Generated by Django 5.1 on 2025-02-25 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_profile_city_alter_profile_number_and_more"),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="job",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="job.job",
            ),
            preserve_default=False,
        ),
    ]
