# Generated by Django 5.1 on 2025-02-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_profile_job"),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="job",
        ),
        migrations.AddField(
            model_name="profile",
            name="jobs",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="job.job"
            ),
        ),
    ]
