# Generated by Django 5.1 on 2025-02-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_remove_profile_job_profile_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(default="Egypt", max_length=100),
        ),
    ]
