# Generated by Django 5.1 on 2024-10-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='write_a_comment',
        ),
    ]
