# Generated by Django 5.1 on 2025-02-27 16:43

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="country",
            field=django_countries.fields.CountryField(default="EG", max_length=2),
        ),
    ]
