# Generated by Django 5.1 on 2025-02-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_job_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="city",
            field=models.CharField(default="tanta", max_length=80),
            preserve_default=False,
        ),
    ]
