# Generated by Django 5.1 on 2025-02-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_job_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="city",
            field=models.CharField(default="Tanta", max_length=80),
        ),
    ]
