# Generated by Django 5.1 on 2025-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0004_alter_job_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="country",
            field=models.CharField(default="EGYPT", max_length=80),
        ),
    ]
